server:
  port: 8089
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
netty:
  port: 1314
logging:
  level:
    snegrid.move.hangar: info

# 项目相关配置
drone:
  name: 机库管控系统
  version: 2.1.1
  copyrightYear: 2023
  profile: /
  addressEnabled: false
  captchaType: math

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 180
