spring:
  application:
    name: move-hangar
  servlet:
    multipart:
      max-file-size: 200MB # 单个文件大小
      max-request-size: 200MB # 单次请求文件总大小
  #redis
  redis:
    host: 47.99.163.33
    port: 6379
    password: 123456
    database: 1
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间
  #mysql
  datasource:
    url: jdbc:mysql://47.99.163.33:3306/move_hangar?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  type-aliases-package: snegrid.move.hangar


#mqtt配置
mqtt:
  broker: tcp://47.99.163.33:1883
  clientId: mqtt_move_hangar_mac_local
  username:
  password:
  #超时时间
  timeout: 10
  #心跳时间
  keepAliveInterval: 60
  #设置消息发布质量
  qos: 0
  #订阅的主题
  topicSub: /sys/info/#,/sys/log/#,/sys/jkcmd/#,/sys/process/#
  #发布的主题
  topicPub: /sys/cmd/#

# Minio配置
minio:
  url: http://47.99.163.33:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: dock-bucket





